---

sudo: required

dist: trusty

language: python

python:
  - 2.7

services:
  - docker

env:
  global:
    - ANSIBLE_FORCE_COLOR: true
    - ANSIBLE_LOG_PATH: './ansible.log'
    - ANSIBLE_ROLES_PATH: '../'
  matrix:
    - DOCKER_NAME: 'ubuntu'
      DOCKER_TAG: '14.04'
    - DOCKER_NAME: 'ubuntu'
      DOCKER_TAG: '16.04'
#    - DOCKER_NAME: 'centos'
#      DOCKER_TAG: '6'
#    - DOCKER_NAME: 'centos/systemd'
#      DOCKER_TAG: 'latest'

before_install:
  - pip install --upgrade --upgrade-strategy only-if-needed ansible docker-py docker-compose
  - docker pull $DOCKER_NAME:$DOCKER_TAG
  - DOCKER_ID="$(docker run -itd --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run $DOCKER_NAME:$DOCKER_TAG | head -c12)"

install:
  - pip install -r ansible-requirements.txt
  - ansible-galaxy install -r requirements.yml

script:
  - yamllint -c .yamllint .
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --syntax-check
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --diff --verbose
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --diff --verbose
  - tail -n 1 ansible.log | grep -Eq 'changed=0 +unreachable=0 +failed=0'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
