---

dist: xenial

language: python

env:
  matrix:
    - LXC_IMAGE: 'images:ubuntu/16.04'
    - LXC_IMAGE: 'images:ubuntu/18.04'
    - LXC_IMAGE: 'images:centos/6'
    - LXC_IMAGE: 'images:centos/7'

before_install:
  - sudo apt-get -y purge lxc-* lxd-* && sudo apt-get -y autoremove
  - sudo snap install lxd && sudo lxd init --preseed < .travis.lxd.yml
  - sudo apt-get -y purge python-openssl && sudo apt-get -y autoremove
  - sudo -H pip install --upgrade --requirement requirements.txt

install:
  - export ROLE=$(echo $TRAVIS_REPO_SLUG | sed 's/^.*\/ansible-role-/\//g')
  - mkdir -p $HOME/.ansible/roles
  - ln -s $TRAVIS_BUILD_DIR $HOME/.ansible/roles/$ROLE
  - ansible-galaxy install --roles-path $HOME/.ansible/roles --role-file ansible-role-requirements.yml

script:
  - sudo ./scripts/run-tests.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
